Update steward to v0.2.2
projectsyn/lieutenant-api pull request #103
Opened 2020-11-13 16:12 UTC by ccremer

Signed-off-by: Chris <github.account@chrigel.net>

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [x] Update the ./CHANGELOG.md.
- [ ] Link this PR to related issues.

2020-11-13 16:21 UTC, corvus-ch requested changes

2020-11-13 16:21 UTC, corvus-ch commented on CHANGELOG.md
> +[#103]: https://github.com/projectsyn/lieutenant-api/pull/103
Missing the line in the Unreleased section

2020-11-16 08:13 UTC, srueg commented on CHANGELOG.md
> +- Update steward to v0.2.2([#103])
```suggestion
- Update steward to v0.2.2 ([#103])
```

2020-11-16 08:14 UTC, srueg approved these changes

2020-11-16 08:43 UTC, corvus-ch requested changes

2020-11-16 08:43 UTC, corvus-ch commented on CHANGELOG.md
> +## Unreleased
```suggestion
## [Unreleased]
```

2020-11-16 08:43 UTC, corvus-ch commented on CHANGELOG.md
> +- Update steward to v0.2.2 ([#103])
```suggestion
### Changed
- Update steward to v0.2.2 ([#103])
```

2020-11-16 08:55 UTC, corvus-ch approved these changes

2020-11-16 08:58 UTC, merged