Add configurable revisions for git repositories
projectsyn/lieutenant-api pull request #90
Opened 2020-10-19 15:34 UTC by corvus-ch

https://github.com/projectsyn/commodore/issues/198 and https://github.com/projectsyn/commodore/issues/171 asks for a way to store git revisions. This builds on top of https://github.com/projectsyn/lieutenant-operator/pull/116 to expose the new fields through the API.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update the ./CHANGELOG.md.
- [x] Link this PR to related issues.
- [x] Update CRD dependencies

2020-10-19 15:37 UTC, corvus-ch commented
@srueg Have I seen correctly: there are no test for the conversion between CRD and API DTOs?

And is it OK to reuse the GitRepo object here? It provides some fields not needed for this use case.

2020-10-19 15:56 UTC, srueg commented
Yes right, there's no explicit tests for the conversion funcs. They're tested to some extent through the "service" tests tough, by using a fake K8s client (so the objects are being converted API->CRDs->API in the tests).

> And is it OK to reuse the GitRepo object here? It provides some fields not needed for this use case.

Hmm, I'd rather create a new type for this (or split the `GitRepo` type). The generated documentation gets quite confusing otherwise.

2020-10-20 15:00 UTC, srueg requested changes
Please extend the tests to make sure the new fields get set correctly

2020-10-20 15:00 UTC, srueg commented on openapi.yaml
> +        revision:
We should probably move this out of the general `GitRepo` type and create a new type (e.g. `TenantGitRepo`) based on `GitRepo` adding the `revision` field there?

2020-10-21 13:01 UTC, srueg approved these changes
Changes look good, please add some tests

2020-10-22 16:03 UTC, srueg approved these changes

2020-10-23 08:04 UTC, merged